package cuccovillo.alessio.jtail.gui;

import java.awt.Frame;
import java.beans.PropertyVetoException;
import javax.swing.DefaultListModel;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;

/**
 *
 * @author alessio
 */
public class AllWindowsDialog extends javax.swing.JDialog {

    private final JInternalFrame[] internalFrames;
    private final DefaultListModel<JInternalFrame> model;

    /**
     * Creates new form AllWindowsDialog
     *
     * @param parent
     * @param internalFrames
     */
    public AllWindowsDialog(Frame parent, JInternalFrame... internalFrames) {
        super(parent, true);
        this.internalFrames = internalFrames;
        model = createListModel();
        initComponents();
        lstWindows.addListSelectionListener((e) -> {
            boolean enable = lstWindows.getSelectedIndex() > -1;
            cmdBringToFront.setEnabled(enable);
            cmdClose.setEnabled(enable);
        });
    }

    private DefaultListModel<JInternalFrame> createListModel() {
        DefaultListModel<JInternalFrame> m = new DefaultListModel<>();
        for (JInternalFrame internalFrame1 : internalFrames) {
            m.addElement(internalFrame1);
        }
        return m;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstWindows = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        cmdBringToFront = new javax.swing.JButton();
        cmdClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manage Windows");
        setResizable(false);

        lstWindows.setModel(model);
        lstWindows.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstWindows.setCellRenderer((list, frame, index, isSelected, cellHasFocus) -> {
            JLabel label=new JLabel(frame.getTitle());
            label.setOpaque(true);
            if (isSelected) {
                label.setBackground(list.getSelectionBackground());
                label.setForeground(list.getSelectionForeground());
            } else {
                label.setBackground(list.getBackground());
                label.setForeground(list.getForeground());
            }
            return label;
        }
    );
    lstWindows.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            lstWindowsMouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(lstWindows);

    cmdBringToFront.setText("Bring to front");
    cmdBringToFront.setEnabled(false);
    cmdBringToFront.setPreferredSize(new java.awt.Dimension(150, 23));
    cmdBringToFront.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cmdBringToFrontActionPerformed(evt);
        }
    });

    cmdClose.setText("Close");
    cmdClose.setEnabled(false);
    cmdClose.setPreferredSize(new java.awt.Dimension(150, 23));
    cmdClose.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cmdCloseActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(cmdBringToFront, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cmdClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(cmdBringToFront, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(cmdClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(6, 6, 6))
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lstWindowsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstWindowsMouseClicked
        if (evt.getClickCount() > 1) {
            bringToFront(lstWindows.getSelectedValue());
        }
    }//GEN-LAST:event_lstWindowsMouseClicked

    private void cmdBringToFrontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBringToFrontActionPerformed
        bringToFront(lstWindows.getSelectedValue());
    }//GEN-LAST:event_cmdBringToFrontActionPerformed

    private void cmdCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCloseActionPerformed
        try {
            lstWindows.getSelectedValue().setClosed(true);
            model.removeElementAt(lstWindows.getSelectedIndex());
            if (model.size() == 0) {
                dispose();
            }
        } catch (PropertyVetoException ignore) {
        }
    }//GEN-LAST:event_cmdCloseActionPerformed

    private void bringToFront(JInternalFrame frame) {
        frame.toFront();
        try {
            frame.setSelected(true);
        } catch (PropertyVetoException ignore) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBringToFront;
    private javax.swing.JButton cmdClose;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<JInternalFrame> lstWindows;
    // End of variables declaration//GEN-END:variables
}
