package cuccovillo.alessio.jtail.gui;

import cuccovillo.alessio.jtaillib.Settings;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.beans.PropertyVetoException;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.KeyStroke;

/**
 *
 * @author alessio
 */
public class JTailGUI extends javax.swing.JFrame {

//    private final Settings settings;
    /**
     * Creates new form JTailGUI
     *
     */
    public JTailGUI() {
        initComponents();
    }

    public static KeyStroke getKeyStroke(int keyEvent) {
        return KeyStroke.getKeyStroke(keyEvent, Toolkit.getDefaultToolkit().getMenuShortcutKeyMask());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuFileOpen = new javax.swing.JMenuItem();
        mnuFileSeparator = new javax.swing.JPopupMenu.Separator();
        mnuFileExit = new javax.swing.JMenuItem();
        mnuWindows = new javax.swing.JMenu();
        mnuWindowsPreviuos = new javax.swing.JMenuItem();
        mnuWindowsNext = new javax.swing.JMenuItem();
        mnuWindowsSelect = new javax.swing.JMenuItem();

        jFileChooser1.setMultiSelectionEnabled(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JTail");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 833, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jDesktopPane1);

        mnuFile.setText("File");

        mnuFileOpen.setAccelerator(getKeyStroke(KeyEvent.VK_O));
        mnuFileOpen.setMnemonic('O');
        mnuFileOpen.setText("Open");
        mnuFileOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFileOpenActionPerformed(evt);
            }
        });
        mnuFile.add(mnuFileOpen);
        mnuFile.add(mnuFileSeparator);

        mnuFileExit.setAccelerator(getKeyStroke(KeyEvent.VK_Q));
        mnuFileExit.setText("Exit");
        mnuFileExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFileExitActionPerformed(evt);
            }
        });
        mnuFile.add(mnuFileExit);

        jMenuBar1.add(mnuFile);

        mnuWindows.setText("Windows");
        mnuWindows.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                mnuWindowsMenuSelected(evt);
            }
        });

        mnuWindowsPreviuos.setAccelerator(getKeyStroke(KeyEvent.VK_LEFT));
        mnuWindowsPreviuos.setText("Previous Window");
        mnuWindowsPreviuos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuWindowsPreviuosActionPerformed(evt);
            }
        });
        mnuWindows.add(mnuWindowsPreviuos);

        mnuWindowsNext.setAccelerator(getKeyStroke(KeyEvent.VK_RIGHT));
        mnuWindowsNext.setText("Next Window");
        mnuWindowsNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuWindowsNextActionPerformed(evt);
            }
        });
        mnuWindows.add(mnuWindowsNext);

        mnuWindowsSelect.setAccelerator(getKeyStroke(KeyEvent.VK_W));
        mnuWindowsSelect.setText("Select Window...");
        mnuWindowsSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuWindowsSelectActionPerformed(evt);
            }
        });
        mnuWindows.add(mnuWindowsSelect);

        jMenuBar1.add(mnuWindows);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        setSize(new java.awt.Dimension(851, 651));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuFileOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFileOpenActionPerformed
        if (jFileChooser1.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            for (File file : jFileChooser1.getSelectedFiles()) {
                Settings settings = Settings.defaultSettings(file);
                JTailInternalForm frame = new JTailInternalForm(settings);
                jDesktopPane1.add(frame);
                frame.toFront();
                try {
                    frame.setSelected(true);
                } catch (PropertyVetoException ignore) {
                }
            }
        }
    }//GEN-LAST:event_mnuFileOpenActionPerformed

    private void mnuFileExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFileExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuFileExitActionPerformed

    private void mnuWindowsSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuWindowsSelectActionPerformed
        new AllWindowsDialog(this, jDesktopPane1.getAllFrames()).setVisible(true);
    }//GEN-LAST:event_mnuWindowsSelectActionPerformed

    private void mnuWindowsPreviuosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuWindowsPreviuosActionPerformed
        jDesktopPane1.selectFrame(false);
    }//GEN-LAST:event_mnuWindowsPreviuosActionPerformed

    private void mnuWindowsNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuWindowsNextActionPerformed
        jDesktopPane1.selectFrame(false);
    }//GEN-LAST:event_mnuWindowsNextActionPerformed

    private void mnuWindowsMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_mnuWindowsMenuSelected
        boolean enabled = jDesktopPane1.getAllFrames().length != 0;
        mnuWindowsNext.setEnabled(enabled);
        mnuWindowsPreviuos.setEnabled(enabled);
        mnuWindowsSelect.setEnabled(enabled);
    }//GEN-LAST:event_mnuWindowsMenuSelected

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem mnuFileExit;
    private javax.swing.JMenuItem mnuFileOpen;
    private javax.swing.JPopupMenu.Separator mnuFileSeparator;
    private javax.swing.JMenu mnuWindows;
    private javax.swing.JMenuItem mnuWindowsNext;
    private javax.swing.JMenuItem mnuWindowsPreviuos;
    private javax.swing.JMenuItem mnuWindowsSelect;
    // End of variables declaration//GEN-END:variables
}
