package cuccovillo.alessio.jtail.gui;

import cuccovillo.alessio.jtaillib.Settings;
import cuccovillo.alessio.jtaillib.controller.TailController;
import java.awt.event.KeyEvent;
import javax.swing.SwingUtilities;

/**
 *
 * @author alessio
 */
public class JTailInternalForm extends javax.swing.JInternalFrame {

    private final TailController tailController;
    public final String fileName;

    /**
     * Creates new form JTailInternalForm
     *
     * @param settings
     */
    public JTailInternalForm(Settings settings) {
        initComponents();
        tailController = new TailController(settings, (c) -> {
            SwingUtilities.invokeLater(() -> {
                jTextArea1.setText(jTextArea1.getText() + c);
            });
        });
        fileName = settings.getFile().toString();
        prepareGUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuTail = new javax.swing.JMenu();
        mnuTailFollowTail = new javax.swing.JCheckBoxMenuItem();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setVisible(true);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        mnuTail.setMnemonic('T');
        mnuTail.setText("Tail");

        mnuTailFollowTail.setAccelerator(JTailGUI.getKeyStroke(KeyEvent.VK_F));
        mnuTailFollowTail.setMnemonic('F');
        mnuTailFollowTail.setSelected(true);
        mnuTailFollowTail.setText("Follow tail");
        mnuTailFollowTail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTailFollowTailActionPerformed(evt);
            }
        });
        mnuTail.add(mnuTailFollowTail);

        jMenuBar1.add(mnuTail);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBounds(0, 0, 573, 520);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuTailFollowTailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTailFollowTailActionPerformed
        if (mnuTailFollowTail.isSelected()) {
            tailController.resumeTail();
        } else {
            tailController.pauseTail();
        }
        setTitle();
    }//GEN-LAST:event_mnuTailFollowTailActionPerformed

    private void prepareGUI() {
        setTitle();
        SwingUtilities.invokeLater(tailController::startTail);
    }

    private void setTitle() {
        super.setTitle(tailController.isPaused() ? fileName + " - PAUSE" : fileName); //To change body of generated methods, choose Tools | Templates.
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JMenu mnuTail;
    private javax.swing.JCheckBoxMenuItem mnuTailFollowTail;
    // End of variables declaration//GEN-END:variables
}
